name: Deploy Worker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Enable and install pnpm
        run: |
          corepack enable
          pnpm install

      - name: Deploy to the correct environment
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          branch=$(git rev-parse --abbrev-ref HEAD)
          echo "Current branch: $branch"
          if [[ "$branch" == "master" ]]; then
            pnpm wrangler deploy --env production
